name: deploy

on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: change permission
        run: |
          sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner/_work/jwp-shopping-order 

      - uses: actions/checkout@v3
      - name: gradle bootjar
        run: |
          chmod +x ./gradlew
          ./gradlew bootjar
      - name: kill 8080 port if exist
        run: |
          if pgrep -f jwp-shopping-order.jar; then
            echo "포트 죽이는 중..."
            kill -16 $(pgrep -f jwp-shopping-order.jar) 
          fi

      - name: deploy
        run: |
          sudo java -jar build/libs/jwp-shopping-order.jar &
